name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install Node and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: |
          npm install

      - name: Package apps
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run postinstall
          npm run build
          npm run package

      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}

      - name: Upload release asset [mac/arm]
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./release/build/Pixel Perfect Checker-4.6.0-arm64.dmg
          asset_name: PixelPerfectChecker-arm64.dmg
          asset_content_type: application/zip

      - name: Upload release asset [mac/intel]
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./release/build/Pixel Perfect Checker-4.6.0.dmg
          asset_name: PixelPerfectChecker.dmg
          asset_content_type: application/zip

      - name: Upload release asset [win]
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./release/build/Pixel Perfect Checker Setup 4.6.0.exe
          asset_name: PixelPerfectChecker.exe
          asset_content_type: application/zip
